### ISSUE TITLE
You have to be in survival for any actions involving the xp storage.

### ISSUE THREAD

**Issue by BowBoy1** [Meridanus/fabric_xp_storage_1.18#23] opened 2022-08-21 17:27 UTC
It seems that you have to be in survival to use the xp storage. It doesn't let you do any xp transfer actions and will not allow you to enable or disable vacuum mode in creative mode.

**Comment by Meridanus** [comment] 2022-08-21 17:42
yes this is intended behavior, maybe i will change this at some point.
whats the benefit to allow creative insertions?

**Comment by BowBoy1** [comment] 2022-08-21 17:47
Allowing creative interaction can be useful for testing purposes when designing farms

**Comment by Meridanus** [comment] 2022-08-21 20:59
Good point, I change this with the next update. Maybe when remove xp while creative it clears it in one go?

**Comment by Meridanus** [comment] 2022-09-04 05:51
fixed with the newest version

**Closed by Meridanus** 2022-09-04 05:51 UTC
